language: node_js
node_js:
  - 12
  - 14
services:
  - postgresql
before_script:
  - psql -f db/install.sql -U postgres
  - PGPASSWORD=acn psql -d acn -f db/structure.sql -U acn
  - PGPASSWORD=acn psql -d acn -f db/data.sql -U acn
script:
  - npm test
